### PR TITLE
Shitcoin

### PR DESCRIPTION
**Pull request by elaineo**

### CODE REVIEW

**Comment by ghost** [comment]
Hm, ICO is not good in general, for 99%, you want to automate that shit? ;)

**Comment by elaineo** [comment]
@dulanov yeah why should ETH get to have all the ponzi coins? :)

**Comment by elaineo** [comment]
OH MAN... I just realized that this project should have been an ICO.... dammit

**Comment by ghost** [comment]
But @elaineo not forget about white paper before!

**Comment by arvicco** [comment]
It's already covered, don't worry @dulanov!

https://github.com/koinster/blockchain-whitepaper-generator

**Comment by arvicco** [comment]
Yes, @elaineo - in order to use this ICO generator, you need a token. You can call it ICO. It will be the ICO of all ICOs. Deep recursion FTW! :)

**Comment by elaineo** [comment]
Instead of calling them ponzi schemes, we should just call them recursive
investments :)

**Comment by arvicco** [comment]
What a magnificent buzzword @elaineo! Sure beats "rich statefulness". Quick, you need to blog about it and immediately buy out all the relevant domains. I feel it will be a big hit in no time!

**Pull request merged**
